from typing import Any, Dict, Generic, List, Optional, Type, TypeVar, Union
from pydantic import BaseModel
from sqlalchemy.orm import Session
from app.db.base_class import Base
from app.models.sync import SyncQueue

ModelType = TypeVar("ModelType", bound=Base)
CreateSchemaType = TypeVar("CreateSchemaType", bound=BaseModel)
UpdateSchemaType = TypeVar("UpdateSchemaType", bound=BaseModel)

class CRUDBase(Generic[ModelType, CreateSchemaType, UpdateSchemaType]):
    def __init__(self, model: Type[ModelType], entity_type: Optional[str] = None):
        """
        CRUD object with default methods to Create, Read, Update, Delete (CRUD).
        
        :param model: A SQLAlchemy model class
        :param entity_type: Entity name for logging to Sync Queue (e.g. 'patient')
        """
        self.model = model
        self.entity_type = entity_type

    def get(self, db: Session, id: Any) -> Optional[ModelType]:
        return db.get(self.model, id)

    def get_multi(
        self, db: Session, *, skip: int = 0, limit: int = 100
    ) -> List[ModelType]:
        return db.query(self.model).offset(skip).limit(limit).all()

    def create(self, db: Session, *, obj_in: CreateSchemaType) -> ModelType:
        if isinstance(obj_in, dict):
            obj_in_data = obj_in
        else:
            obj_in_data = obj_in.model_dump()
            
        db_obj = self.model(**obj_in_data)
        db.add(db_obj)
        db.flush()  # Populates ID (if generated by default) and defaults in the transaction
        
        # Log to Sync Queue (outbox pattern)
        if self.entity_type:
            sync_entry = SyncQueue(
                entity_type=self.entity_type,
                entity_id=db_obj.id,
                operation_type="CREATE",
                sync_status="PENDING"
            )
            db.add(sync_entry)
            
        return db_obj

    def update(
        self,
        db: Session,
        *,
        db_obj: ModelType,
        obj_in: Union[UpdateSchemaType, Dict[str, Any]]
    ) -> ModelType:
        if isinstance(obj_in, dict):
            update_data = obj_in
        else:
            update_data = obj_in.model_dump(exclude_unset=True)
            
        for field in update_data:
            if hasattr(db_obj, field):
                setattr(db_obj, field, update_data[field])
                
        db.add(db_obj)
        db.flush()
        
        # Log to Sync Queue (outbox pattern)
        if self.entity_type:
            sync_entry = SyncQueue(
                entity_type=self.entity_type,
                entity_id=db_obj.id,
                operation_type="UPDATE",
                sync_status="PENDING"
            )
            db.add(sync_entry)
            
        return db_obj

    def remove(self, db: Session, *, id: Any) -> Optional[ModelType]:
        obj = db.get(self.model, id)
        if obj:
            db.delete(obj)
            
            # Log to Sync Queue (outbox pattern)
            if self.entity_type:
                sync_entry = SyncQueue(
                    entity_type=self.entity_type,
                    entity_id=id,
                    operation_type="DELETE",
                    sync_status="PENDING"
                )
                db.add(sync_entry)
                
        return obj
